#!/bin/bash
docker-compose up -d
cd src
mix deps.get
if [ -d "assets/node_modules" ]; then
  cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development
  cd ..
fi
mix ecto.create
mix phx.server
